### ISSUE TITLE
typo helm chart pvc path is broken

### ISSUE THREAD

**Issue by marijusGood** [christianknell/helm-charts#1024]
The volumeMounts for fileadmin and typo3conf are _/fileadmin_ and _/typo3conf_ respectively. With this path, when the container dies, typo3 asks to register the db and your account again, indicating that the volumes did not work.

To fix this problem, the volumes should be _/var/www/html/fileadmin_  _/var/www/html/typo3conf_

as seen here:
`kubectl exec -it typo3-66b5f484cd-q2szd -n typo3 -- /bin/bash`
`root@typo3-66b5f484cd-q2szd:/var/www/html# ls`
`fileadmin  index.php  typo3  typo3_src  typo3_src-12.4.6  typo3conf  typo3temp  uploads`

I have tested it on the initially provided container 11.5 and the latest one and it works all fine.

**Comment by christianknell** [comment]
fixed with v1.19.1 of the Helm Chart
