### ISSUE TITLE
Preset the DB connections for typo3

### ISSUE THREAD

**Issue by marijusGood** [christianknell/helm-charts#1056]
Hi team,
we want to preset the DB connection settings for typo3 whenever the container starts up as at the moment once it starts we need to go through the setup page, do you think it would be possible to preset these variables?

Note:
We need this feature because we would like to use our own hosted DB instead of what is created in the helm chart.

**Comment by christianknell** [comment]
Hi @marijusGood,
presetting the DB connection is not possible to my knowledge. This is a limitation of the Docker Image. Maybe you can open a ticket there?

The issue with the non-persisted db settings has been fixed here https://github.com/christianknell/helm-charts/issues/1024.

**Comment by marijusGood** [comment]
That makes sense, thanks for the help!
