### ISSUE TITLE
Configure input parameters pushgateway-address

### ISSUE THREAD

**Issue by davispalomino** [christianknell/helm-charts#119]
https://github.com/christianknell/helm-charts/blob/2154f3482062ce5e52d42fd4c7809f786aaa6934/charts/popeye/templates/cronjob.yaml#L34

```yaml
- args:
   - -o 
   - prometheus
   -  --pushgateway-address
   - prometheus-pushgateway:9091
   -  --force-exit-zero=true
```
Thank you for your support, I look forward to your comments.

Best regards

**Comment by christianknell** [comment]
@davispalomino thanks for the idea. Can you provide me with some documentation for this feature of Popeye? Then I will add the needed values to the Chart.
