### ISSUE TITLE
how can we update the default deployment values such as email transport host details etc

### ISSUE THREAD

**Issue by vasudevbannaravuri** [christianknell/helm-charts#324]
how can we update the default deployment values such as email transport host details etc

**Comment by christianknell** [comment]
Which Helm chart?

**Comment by vasudevbannaravuri** [comment]
I am talking about passbolt-ha helm chart. Trying to use this helm chart for my project and by default smtp is getting updated as email transport host. I have configured external mail server and wanted to use the same in my email transport host.

**Comment by christianknell** [comment]
The passbolt-ha chart is using the passbolt chart by cnieg under the hood. So you simply can use the values defined over there: https://artifacthub.io/packages/helm/cnieg/passbolt. Hope this helps.
