### ISSUE TITLE
baserow: smtpPassword is not fed to secret, instead undocumented "password" field is used

### ISSUE THREAD

**Issue by Freundschaft** [christianknell/helm-charts#558]
heyhey, thanks for the charts, ive been trying to get email to work for a bit using the chart, and found an issue in the value schema which refers to the smtp password as: "smtpPassword" https://github.com/christianknell/helm-charts/blob/c6aa64c8288f924e6c24ac8292ddae2242a136ad/charts/baserow/values.schema.json#L317

but then in the secrets template, the field smtppassword is ignored and email.password is used instead https://github.com/christianknell/helm-charts/blob/main/charts/baserow/templates/email-secret.yaml#L7

I can confirm that it works by setting email.password and not with email.smtppassword

Cheers

**Comment by christianknell** [comment]
Will fix this with next release

**Comment by christianknell** [comment]
Latest release v1.10.2 of the Chart has this fixed. Use the documented smtpPassword instead of the password field please.
