### ISSUE TITLE
baserow: when using external postgres, parameters arent set for celery

### ISSUE THREAD

**Issue by Freundschaft** [christianknell/helm-charts#588]
I am using an external postgres, which generally works, but celery doesnt seem to get the correct password, which results in jobs not working, can you check if external postgres sets the environment / secret for celery correctly?
After setting the password manually in extra_envs of celery, it works, but thats just a temporary fix.

**Comment by nigel-gott** [comment]
This MR is my attempt to fix this exact bug: https://github.com/christianknell/helm-charts/pull/581

**Comment by Freundschaft** [comment]
looks fine from my side
