### ISSUE TITLE
Path for externalPostgresql.auth in Documentation doesn't reflect Chart Values

### ISSUE THREAD

**Issue by lbrpsoftware** [christianknell/helm-charts#642]
Hi Christian,

Thank for the excellent Chart.
Found a minor "bug":

The Chart Values for the **externalPostgresql** settings don't have the **auth** path (like Redis), as documented.

Regards

**Comment by christianknell** [comment]
@lbrpsoftware what Chart are you talking about?

**Comment by lbrpsoftware** [comment]
Oh yeah,
It's the Kutt Chart

**Comment by christianknell** [comment]
Thanks. Will look into this.

**Comment by christianknell** [comment]
Changed in latest release of kutt: 2.2.0.
